name: dbt-workflow-test-5
version: v1
type: workflow
tags:
  - workflow
description: DBT Sample Workflow
workspace: public
workflow:
  dag:
    - name: dbt-workflow-job-v2
      title: dbt Sample Test Jobs
      spec:
        stack: dbt+python:1.0
        compute: runnable-default
        resources:
          requests:
            cpu: 1000m
            memory: 250Mi
          limits:
            cpu: 1000m
            memory: 250Mi
        logLevel: DEBUG # WARNING, ERROR, DEBUG
        stackSpec:
          profiles:
            dbt_trino:
              target: dev
              outputs:
                dev:
                  type: trino
                  method: ldap
                  user: yogeshkhangode
                  password: eyJ0b2tlbiI6ImMzVndaWEp6WlhRdU9UZ3lNMll3WlRZdFpqYzFPQzAwTkdFd0xUazNNV1F0WlRReE9HUmxaVGN4TkRGaiIsImNsdXN0ZXIiOiJzeXN0ZW0ifQ==
                  host: tcp.emerging-hawk.dataos.app
                  database: icebase
                  schema: retail
                  port: 7432
                  threads: 1
          dbt_project:
            name: 'dbt_test_3'
            version: '1.0.0'
            config-version: 2
            model-paths: ["models"]
            test-paths: ["tests"]
            profile: 'dbt_trino'
            models:
              dbt_test_3:
                analysis:
                  +materialized: view
          dbt_packages:
            packages:
              - git: "https://github.com/darpan-vyas/dbt-test-1.git"