name: "dbt-v1"
version: v1alpha
type: stack
layer: user
description: "dbt workflow stack version 1"
stack:
  name: dbt
  version: "1.0"
  flavor: "python"
  reconciler: "stackManager"
#  dataOsAddressJqFilters:
#    - .inputs[].dataset
  secretProjection:
    type: "envVars"
  image:
    registry: docker.io
    repository: modern123
    image: dbt_stack
    tag: 1.1
    # auth:
    #   imagePullSecret: dataos-container-registry
  command:
    - python3
  arguments:
    - main.py
  stackSpecValueSchema:
    jsonSchema: |
      {"$schema":"http://json-schema.org/draft-04/schema#","type":"object","properties":{"dbt_project":{"type":"object"},"dbt_packages":{"type":"object"},"profiles":{"type":"object"}}}
  workflowJobConfig:
    configFileTemplate: |
      dbt_project.yml: |
      {{ toYaml .ApplicationSpec.StackSpec.dbt_project | indent 2 }}
      packages.yml: |
      {{ toYaml .ApplicationSpec.StackSpec.dbt_packages | indent 2 }}
      profiles.yml: |
      {{ toYaml .ApplicationSpec.StackSpec.profiles | indent 2 }}